// Downloads the exact Google Fonts files that src/components/theme.ts uses (same URLs as @remotion/google-fonts)
// into public/fonts/, so renders work offline / behind proxies where the headless browser cannot reach fonts.gstatic.com.
// Run: node tools/fetch-fonts.mjs   (writes public/fonts/*.woff2 + src/components/fontManifest.json)
import fs from 'node:fs';
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
const require = createRequire(import.meta.url);
const WANT = [
  ['Inter', 'normal', ['400', '500', '600', '700', '800', '900']],
  ['SourceSerif4', 'normal', ['400', '600']],
  ['InstrumentSerif', 'normal', ['400']],
  ['InstrumentSerif', 'italic', ['400']],
];
const manifest = [];
for (const [pkg, style, weights] of WANT) {
  const info = require(`@remotion/google-fonts/${pkg}`).getInfo();
  for (const w of weights) {
    const url = info.fonts[style][w].latin;
    const file = `${pkg}-${style}-${w}.woff2`;
    fs.mkdirSync('public/fonts', { recursive: true }); if (!fs.existsSync(`public/fonts/${file}`)) execFileSync('curl', ['-sSfL', '-o', `public/fonts/${file}`, url]);
    manifest.push({ family: info.fontFamily, style, weight: w, file, unicodeRange: info.unicodeRanges?.latin });
  }
}
fs.writeFileSync('src/components/fontManifest.json', JSON.stringify(manifest, null, 1));
console.log('fonts:', manifest.length);

// Embed the files as data URIs (deduplicated: Google serves one variable file for all weights of a family/style),
// so the renderer never fetches fonts at all (fetching via staticFile intermittently stalled delayRender).
const byFile = new Map();
for (const m of manifest) {
  const buf = fs.readFileSync(`public/fonts/${m.file}`);
  const key = `${m.family}|${m.style}|${buf.toString('base64').length}|${buf.subarray(0, 64).toString('hex')}`;
  const e = byFile.get(key) ?? { family: m.family, style: m.style, weights: [], unicodeRange: m.unicodeRange, data: buf.toString('base64') };
  e.weights.push(Number(m.weight)); byFile.set(key, e);
}
const faces = [...byFile.values()].map((e) => ({ family: e.family, style: e.style, weight: e.weights.length > 1 ? `${Math.min(...e.weights)} ${Math.max(...e.weights)}` : String(e.weights[0]), unicodeRange: e.unicodeRange, src: `data:font/woff2;base64,${e.data}` }));
fs.writeFileSync('src/components/fontData.ts', `// GENERATED by tools/fetch-fonts.mjs - do not edit.\nexport const FONT_FACES: { family: string; style: string; weight: string; unicodeRange: string; src: string }[] = ${JSON.stringify(faces)};\n`);
console.log('faces embedded:', faces.map((f) => `${f.family} ${f.style} ${f.weight}`).join(', '));
